### ISSUE TITLE
Enable the feature by clicking the gutter decorations (icons)

### ISSUE THREAD

**Issue by CoolLoong** [itsyaasir/rust-feature-toggle#6]

**Comment by itsyaasir** [comment]
Hi Thanks for the suggestions, this is the next thing I am implementing. Let me try to get this done in this weekend.

**Comment by itsyaasir** [comment]
Hi, I did more research on this and it seems that vscode doesn't support clicking of the icon in the gutters. 
Sources here: https://github.com/microsoft/codetour/issues/131 and https://github.com/microsoft/vscode/issues/175945#issuecomment-1466438453

But I did find another way I can do this easily and that is using codelens.

Screenshot below :

<img width="324" alt="image" src="https://github.com/user-attachments/assets/914c8b43-6ebe-4438-aa12-82043f8ed72d">

**Comment by itsyaasir** [comment]
I have rolled out this feature in pre-release v0.3.0, switch to that version please
